name: Generate documentation

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: un
        shell: bash
        run: |
          ls
